//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fina_News_System_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.NewsCompanyCodes = new HashSet<NewsCompanyCodes>();
        }
    
        public int ID { get; set; }
        public string Version { get; set; }
        public System.DateTime TDate { get; set; }
        public string Title { get; set; }
        public string BodyText { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ShowTypeID { get; set; }
        public Nullable<int> ModuleTypeID { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual ModuleTypes ModuleTypes { get; set; }
        public virtual ShowTypes ShowTypes { get; set; }
        public virtual Types Types { get; set; }
        public virtual ICollection<NewsCompanyCodes> NewsCompanyCodes { get; set; }
    }
}
