//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fina_News_System_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCompanyCodes
    {
        public int ID { get; set; }
        public int GeneralID { get; set; }
        public string Code { get; set; }
    
        public virtual News News { get; set; }
    }
}
